spring:
  application:
    name: modulo-administracion
  profiles:
    default: dev

---
spring:
  config:
    activate:
      on-profile: dev
    import: "configserver:http://localhost:8888"

springdoc:
  swagger-ui:
    config-url: /administracion/v3/api-docs/swagger-config
    url: /administracion/v3/api-docs

---
spring:
  config:
    activate:
      on-profile: docker
    import: "configserver:http://configserver:8888"
